/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Defines a sorter used to sort results from [SearchVendors](https://developer.squareup.com/reference/square_2024-01-18/vendors-api/search-vendors).
type SearchVendorsRequestSort struct {
	// Specifies the sort key to sort the returned vendors.
	Field string `json:"field,omitempty"`
	// Specifies the sort order for the returned vendors.
	Order string `json:"order,omitempty"`
}
