/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Sets the day of the week and hour of the day that a business starts a workweek. This is used to calculate overtime pay.
type WorkweekConfig struct {
	// The UUID for this object.
	Id string `json:"id,omitempty"`
	// The day of the week on which a business week starts for compensation purposes.
	StartOfWeek string `json:"start_of_week"`
	// The local time at which a business week starts. Represented as a string in `HH:MM` format (`HH:MM:SS` is also accepted, but seconds are truncated).
	StartOfDayLocalTime string `json:"start_of_day_local_time"`
	// Used for resolving concurrency issues. The request fails if the version provided does not match the server version at the time of the request. If not provided, Square executes a blind write; potentially overwriting data from another write.
	Version int32 `json:"version,omitempty"`
	// A read-only timestamp in RFC 3339 format; presented in UTC.
	CreatedAt string `json:"created_at,omitempty"`
	// A read-only timestamp in RFC 3339 format; presented in UTC.
	UpdatedAt string `json:"updated_at,omitempty"`
}
