/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Defines output parameters in a response of the  [SwapPlan](https://developer.squareup.com/reference/square_2024-01-18/subscriptions-api/swap-plan) endpoint.
type SwapPlanResponse struct {
	// Errors encountered during the request.
	Errors       []ModelError  `json:"errors,omitempty"`
	Subscription *Subscription `json:"subscription,omitempty"`
	// A list of a `SWAP_PLAN` action created by the request.
	Actions []SubscriptionAction `json:"actions,omitempty"`
}
