/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Represents a query used to search for loyalty events.
type LoyaltyEventQuery struct {
	Filter *LoyaltyEventFilter `json:"filter,omitempty"`
}
