/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// V1SettlementEntry
type V1SettlementEntry struct {
	// The settlement's unique identifier.
	PaymentId string `json:"payment_id,omitempty"`
	// The settlement's current status.
	Type_ string `json:"type,omitempty"`
	AmountMoney *V1Money `json:"amount_money,omitempty"`
	FeeMoney *V1Money `json:"fee_money,omitempty"`
}
