/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Defines output parameters in a response of the [DeleteSubscriptionAction](https://developer.squareup.com/reference/square_2024-01-18/subscriptions-api/delete-subscription-action) endpoint.
type DeleteSubscriptionActionResponse struct {
	// Errors encountered during the request.
	Errors       []ModelError  `json:"errors,omitempty"`
	Subscription *Subscription `json:"subscription,omitempty"`
}
