/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A request to update a `BreakType`.
type UpdateBreakTypeRequest struct {
	BreakType *BreakType `json:"break_type"`
}
