/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// LoyaltyPromotionTriggerLimitInterval : Indicates the time period that the [trigger limit](https://developer.squareup.com/reference/square_2024-01-18/objects/LoyaltyPromotionTriggerLimit) applies to, which is used to determine the number of times a buyer can earn points for a [loyalty promotion](https://developer.squareup.com/reference/square_2024-01-18/objects/LoyaltyPromotion).
type LoyaltyPromotionTriggerLimitInterval string

// List of LoyaltyPromotionTriggerLimitInterval
const (
	ALL_TIME_LoyaltyPromotionTriggerLimitInterval LoyaltyPromotionTriggerLimitInterval = "ALL_TIME"
	DAY_LoyaltyPromotionTriggerLimitInterval LoyaltyPromotionTriggerLimitInterval = "DAY"
)
