/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents a [RetrieveLoyaltyPromotionPromotions](https://developer.squareup.com/reference/square_2024-01-18/loyalty-api/retrieve-loyalty-promotion) request.
type RetrieveLoyaltyPromotionRequest struct {
}
