/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// ShiftFilterStatus : Specifies the `status` of `Shift` records to be returned.
type ShiftFilterStatus string

// List of ShiftFilterStatus
const (
	OPEN_ShiftFilterStatus   ShiftFilterStatus = "OPEN"
	CLOSED_ShiftFilterStatus ShiftFilterStatus = "CLOSED"
)
