/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient : Standard ingredients for food and beverage items that are recommended on item creation.
type CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient string

// List of CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient
const (
	CELERY_CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient      CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient = "CELERY"
	CRUSTACEANS_CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient = "CRUSTACEANS"
	EGGS_CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient        CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient = "EGGS"
	FISH_CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient        CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient = "FISH"
	GLUTEN_CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient      CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient = "GLUTEN"
	LUPIN_CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient       CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient = "LUPIN"
	MILK_CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient        CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient = "MILK"
	MOLLUSCS_CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient    CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient = "MOLLUSCS"
	MUSTARD_CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient     CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient = "MUSTARD"
	PEANUTS_CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient     CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient = "PEANUTS"
	SESAME_CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient      CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient = "SESAME"
	SOY_CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient         CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient = "SOY"
	SULPHITES_CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient   CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient = "SULPHITES"
	TREE_NUTS_CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient   CatalogItemFoodAndBeverageDetailsIngredientStandardIngredient = "TREE_NUTS"
)
