/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// The request object for the [UpdateLocation](https://developer.squareup.com/reference/square_2024-01-18/locations-api/update-location) endpoint.
type UpdateLocationRequest struct {
	Location *Location `json:"location,omitempty"`
}
