/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// A request for a set of `WorkweekConfig` objects.
type ListWorkweekConfigsRequest struct {
	// The maximum number of `WorkweekConfigs` results to return per page.
	Limit int32 `json:"limit,omitempty"`
	// A pointer to the next page of `WorkweekConfig` results to fetch.
	Cursor string `json:"cursor,omitempty"`
}
