/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// ArchivedState : Defines the values for the `archived_state` query expression  used in [SearchCatalogItems](https://developer.squareup.com/reference/square_2024-01-18/catalog-api/search-catalog-items)  to return the archived, not archived or either type of catalog items.
type ArchivedState string

// List of ArchivedState
const (
	NOT_ARCHIVED_ArchivedState ArchivedState = "ARCHIVED_STATE_NOT_ARCHIVED"
	ARCHIVED_ArchivedState ArchivedState = "ARCHIVED_STATE_ARCHIVED"
	ALL_ArchivedState ArchivedState = "ARCHIVED_STATE_ALL"
)
