/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The search criteria for the loyalty accounts.
type SearchLoyaltyAccountsRequestLoyaltyAccountQuery struct {
	// The set of mappings to use in the loyalty account search.    This cannot be combined with `customer_ids`.    Max: 30 mappings
	Mappings []LoyaltyAccountMapping `json:"mappings,omitempty"`
	// The set of customer IDs to use in the loyalty account search.    This cannot be combined with `mappings`.    Max: 30 customer IDs
	CustomerIds []string `json:"customer_ids,omitempty"`
}
