/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents a payout fee that can incur as part of a payout.
type PayoutFee struct {
	AmountMoney *Money `json:"amount_money,omitempty"`
	// The timestamp of when the fee takes effect, in RFC 3339 format.
	EffectiveAt string `json:"effective_at,omitempty"`
	// The type of fee assessed as part of the payout.
	Type_ string `json:"type,omitempty"`
}
