/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

type BatchRetrieveCatalogObjectsResponse struct {
	// Any errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
	// A list of [CatalogObject](https://developer.squareup.com/reference/square_2024-01-18/objects/CatalogObject)s returned.
	Objects []CatalogObject `json:"objects,omitempty"`
	// A list of [CatalogObject](https://developer.squareup.com/reference/square_2024-01-18/objects/CatalogObject)s referenced by the object in the `objects` field.
	RelatedObjects []CatalogObject `json:"related_objects,omitempty"`
}
