/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// BusinessAppointmentSettingsAlignmentTime : Time units of a service duration for bookings.
type BusinessAppointmentSettingsAlignmentTime string

// List of BusinessAppointmentSettingsAlignmentTime
const (
	SERVICE_DURATION_BusinessAppointmentSettingsAlignmentTime BusinessAppointmentSettingsAlignmentTime = "SERVICE_DURATION"
	QUARTER_HOURLY_BusinessAppointmentSettingsAlignmentTime BusinessAppointmentSettingsAlignmentTime = "QUARTER_HOURLY"
	HALF_HOURLY_BusinessAppointmentSettingsAlignmentTime BusinessAppointmentSettingsAlignmentTime = "HALF_HOURLY"
	HOURLY_BusinessAppointmentSettingsAlignmentTime BusinessAppointmentSettingsAlignmentTime = "HOURLY"
)
