/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Identifies the sort field and sort order.
type InvoiceSort struct {
	// The field to use for sorting.
	Field string `json:"field"`
	// The order to use for sorting the results.
	Order string `json:"order,omitempty"`
}
