/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// SubscriptionStatus : Supported subscription statuses.
type SubscriptionStatus string

// List of SubscriptionStatus
const (
	PENDING_SubscriptionStatus     SubscriptionStatus = "PENDING"
	ACTIVE_SubscriptionStatus      SubscriptionStatus = "ACTIVE"
	CANCELED_SubscriptionStatus    SubscriptionStatus = "CANCELED"
	DEACTIVATED_SubscriptionStatus SubscriptionStatus = "DEACTIVATED"
	PAUSED_SubscriptionStatus      SubscriptionStatus = "PAUSED"
)
