/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Defines input parameters in a request to the  [RetrieveSubscription](https://developer.squareup.com/reference/square_2024-01-18/subscriptions-api/retrieve-subscription) endpoint.
type RetrieveSubscriptionRequest struct {
	// A query parameter to specify related information to be included in the response.   The supported query parameter values are:   - `actions`: to include scheduled actions on the targeted subscription.
	Include string `json:"include,omitempty"`
}
