/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// TransactionType : The transaction type used in the disputed payment.
type TransactionType string

// List of TransactionType
const (
	DEBIT_TransactionType  TransactionType = "DEBIT"
	CREDIT_TransactionType TransactionType = "CREDIT"
)
