/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details about a refund's destination.
type DestinationDetails struct {
	CardDetails *CardRefundDetails `json:"card_details,omitempty"`
}
