/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Represents additional data for rules with the `SPEND` accrual type.
type LoyaltyProgramAccrualRuleSpendData struct {
	AmountMoney *Money `json:"amount_money"`
	// The IDs of any `CATEGORY` catalog objects that are excluded from points accrual.  You can use the [BatchRetrieveCatalogObjects](https://developer.squareup.com/reference/square_2024-01-18/catalog-api/batch-retrieve-catalog-objects) endpoint to retrieve information about the excluded categories.
	ExcludedCategoryIds []string `json:"excluded_category_ids,omitempty"`
	// The IDs of any `ITEM_VARIATION` catalog objects that are excluded from points accrual.  You can use the [BatchRetrieveCatalogObjects](https://developer.squareup.com/reference/square_2024-01-18/catalog-api/batch-retrieve-catalog-objects) endpoint to retrieve information about the excluded item variations.
	ExcludedItemVariationIds []string `json:"excluded_item_variation_ids,omitempty"`
	// Indicates how taxes should be treated when calculating the purchase amount used for points accrual.
	TaxMode string `json:"tax_mode"`
}
