/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Response payload for the [BulkRetrieveTeamMemberBookingProfiles](https://developer.squareup.com/reference/square_2024-01-18/bookings-api/bulk-retrieve-team-member-booking-profiles) endpoint.
type BulkRetrieveTeamMemberBookingProfilesResponse struct {
	// The returned team members' booking profiles, as a map with `team_member_id` as the key and [TeamMemberBookingProfile](https://developer.squareup.com/reference/square_2024-01-18/objects/TeamMemberBookingProfile) the value.
	TeamMemberBookingProfiles map[string]RetrieveTeamMemberBookingProfileResponse `json:"team_member_booking_profiles,omitempty"`
	// Errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
}
