/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

type DeviceStatusCategory string

// List of DeviceStatusCategory
const (
	AVAILABLE_DeviceStatusCategory       DeviceStatusCategory = "AVAILABLE"
	NEEDS_ATTENTION_DeviceStatusCategory DeviceStatusCategory = "NEEDS_ATTENTION"
	OFFLINE_DeviceStatusCategory         DeviceStatusCategory = "OFFLINE"
)
