/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1Device struct {
	// The device's Square-issued ID.
	Id string `json:"id,omitempty"`
	// The device's merchant-specified name.
	Name string `json:"name,omitempty"`
}
