/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// EcomVisibility : Determines item visibility in Ecom (Online Store) and Online Checkout.
type EcomVisibility string

// List of EcomVisibility
const (
	UNINDEXED_EcomVisibility   EcomVisibility = "UNINDEXED"
	UNAVAILABLE_EcomVisibility EcomVisibility = "UNAVAILABLE"
	HIDDEN_EcomVisibility      EcomVisibility = "HIDDEN"
	VISIBLE_EcomVisibility     EcomVisibility = "VISIBLE"
)
