/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Describes a `PublishInvoice` request.
type PublishInvoiceRequest struct {
	// The version of the [invoice](https://developer.squareup.com/reference/square_2024-01-18/objects/Invoice) to publish. This must match the current version of the invoice; otherwise, the request is rejected.
	Version int32 `json:"version"`
	// A unique string that identifies the `PublishInvoice` request. If you do not  provide `idempotency_key` (or provide an empty string as the value), the endpoint  treats each request as independent.  For more information, see [Idempotency](https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency).
	IdempotencyKey string `json:"idempotency_key,omitempty"`
}
