/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MerchantStatus string

// List of MerchantStatus
const (
	ACTIVE_MerchantStatus MerchantStatus = "ACTIVE"
	INACTIVE_MerchantStatus MerchantStatus = "INACTIVE"
)
