/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// DataCollectionOptionsInputType : Describes the input type of the data.
type DataCollectionOptionsInputType string

// List of DataCollectionOptionsInputType
const (
	EMAIL_DataCollectionOptionsInputType DataCollectionOptionsInputType = "EMAIL"
	PHONE_NUMBER_DataCollectionOptionsInputType DataCollectionOptionsInputType = "PHONE_NUMBER"
)
