/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// BusinessBookingProfileBookingPolicy : Policies for accepting bookings.
type BusinessBookingProfileBookingPolicy string

// List of BusinessBookingProfileBookingPolicy
const (
	ACCEPT_ALL_BusinessBookingProfileBookingPolicy          BusinessBookingProfileBookingPolicy = "ACCEPT_ALL"
	REQUIRES_ACCEPTANCE_BusinessBookingProfileBookingPolicy BusinessBookingProfileBookingPolicy = "REQUIRES_ACCEPTANCE"
)
