/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// LocationType : A location's type.
type LocationType string

// List of LocationType
const (
	PHYSICAL_LocationType LocationType = "PHYSICAL"
	MOBILE_LocationType   LocationType = "MOBILE"
)
