/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// ShiftStatus : Enumerates the possible status of a `Shift`.
type ShiftStatus string

// List of ShiftStatus
const (
	OPEN_ShiftStatus ShiftStatus = "OPEN"
	CLOSED_ShiftStatus ShiftStatus = "CLOSED"
)
