/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Additional details about Afterpay payments.
type AfterpayDetails struct {
	// Email address on the buyer's Afterpay account.
	EmailAddress string `json:"email_address,omitempty"`
}
