/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// DeviceComponentDetailsExternalPower : An enum for ExternalPower.
type DeviceComponentDetailsExternalPower string

// List of DeviceComponentDetailsExternalPower
const (
	AVAILABLE_CHARGING_DeviceComponentDetailsExternalPower DeviceComponentDetailsExternalPower = "AVAILABLE_CHARGING"
	AVAILABLE_NOT_IN_USE_DeviceComponentDetailsExternalPower DeviceComponentDetailsExternalPower = "AVAILABLE_NOT_IN_USE"
	UNAVAILABLE_DeviceComponentDetailsExternalPower DeviceComponentDetailsExternalPower = "UNAVAILABLE"
	AVAILABLE_INSUFFICIENT_DeviceComponentDetailsExternalPower DeviceComponentDetailsExternalPower = "AVAILABLE_INSUFFICIENT"
)
