/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Represents a [ListLocationCustomAttributeDefinitions](https://developer.squareup.com/reference/square_2024-01-18/location-custom-attributes-api/list-location-custom-attribute-definitions) request.
type ListLocationCustomAttributeDefinitionsRequest struct {
	// Filters the `CustomAttributeDefinition` results by their `visibility` values.
	VisibilityFilter string `json:"visibility_filter,omitempty"`
	// The maximum number of results to return in a single paged response. This limit is advisory. The response might contain more or fewer results. The minimum value is 1 and the maximum value is 100. The default value is 20. For more information, see [Pagination](https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination).
	Limit int32 `json:"limit,omitempty"`
	// The cursor returned in the paged response from the previous call to this endpoint. Provide this cursor to retrieve the next page of results for your original request. For more information, see [Pagination](https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination).
	Cursor string `json:"cursor,omitempty"`
}
