/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// A request to redeem a loyalty reward.
type RedeemLoyaltyRewardRequest struct {
	// A unique string that identifies this `RedeemLoyaltyReward` request.  Keys can be any valid string, but must be unique for every request.
	IdempotencyKey string `json:"idempotency_key"`
	// The ID of the [location](https://developer.squareup.com/reference/square_2024-01-18/objects/Location) where the reward is redeemed.
	LocationId string `json:"location_id"`
}
