/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// VisibilityFilter : Enumeration of visibility-filter values used to set the ability to view custom attributes or custom attribute definitions.
type VisibilityFilter string

// List of VisibilityFilter
const (
	ALL_VisibilityFilter VisibilityFilter = "ALL"
	READ_VisibilityFilter VisibilityFilter = "READ"
	READ_WRITE_VisibilityFilter VisibilityFilter = "READ_WRITE"
)
