/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Defines the response returned by [UpdatePayment](https://developer.squareup.com/reference/square_2024-01-18/payments-api/update-payment).
type UpdatePaymentResponse struct {
	// Any errors that occurred during the request.
	Errors  []ModelError `json:"errors,omitempty"`
	Payment *Payment     `json:"payment,omitempty"`
}
