/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Defines the fields that are included in the response body of a request to the [RegisterDomain](https://developer.squareup.com/reference/square_2024-01-18/apple-pay-api/register-domain) endpoint.  Either `errors` or `status` are present in a given response (never both).
type RegisterDomainResponse struct {
	// Any errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
	// The status of the domain registration.  See [RegisterDomainResponseStatus](https://developer.squareup.com/reference/square_2024-01-18/enums/RegisterDomainResponseStatus) for possible values.
	Status string `json:"status,omitempty"`
}
