/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

type ConfirmationDecision struct {
	// The buyer's decision to the displayed terms.
	HasAgreed bool `json:"has_agreed,omitempty"`
}
