/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Defines input parameters in a request to the [ChangeBillingAnchorDate](https://developer.squareup.com/reference/square_2024-01-18/subscriptions-api/change-billing-anchor-date) endpoint.
type ChangeBillingAnchorDateRequest struct {
	// The anchor day for the billing cycle.
	MonthlyBillingAnchorDate int32 `json:"monthly_billing_anchor_date,omitempty"`
	// The `YYYY-MM-DD`-formatted date when the scheduled `BILLING_ANCHOR_CHANGE` action takes place on the subscription.  When this date is unspecified or falls within the current billing cycle, the billing anchor date is changed immediately.
	EffectiveDate string `json:"effective_date,omitempty"`
}
