/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// A `Shift` search query filter parameter that sets a range of days that a `Shift` must start or end in before passing the filter condition.
type ShiftWorkday struct {
	DateRange *DateRange `json:"date_range,omitempty"`
	// The strategy on which the dates are applied.
	MatchShiftsBy string `json:"match_shifts_by,omitempty"`
	// Location-specific timezones convert workdays to datetime filters. Every location included in the query must have a timezone or this field must be provided as a fallback. Format: the IANA timezone database identifier for the relevant timezone.
	DefaultTimezone string `json:"default_timezone,omitempty"`
}
