/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ActionCancelReason string

// List of ActionCancelReason
const (
	BUYER_CANCELED_ActionCancelReason ActionCancelReason = "BUYER_CANCELED"
	SELLER_CANCELED_ActionCancelReason ActionCancelReason = "SELLER_CANCELED"
	TIMED_OUT_ActionCancelReason ActionCancelReason = "TIMED_OUT"
)
