/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Describes the pricing for the subscription.
type SubscriptionPricing struct {
	// RELATIVE or STATIC
	Type_ string `json:"type,omitempty"`
	// The ids of the discount catalog objects
	DiscountIds []string `json:"discount_ids,omitempty"`
	PriceMoney *Money `json:"price_money,omitempty"`
}
