/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents an [AccumulateLoyaltyPoints](https://developer.squareup.com/reference/square_2024-01-18/loyalty-api/accumulate-loyalty-points) request.
type AccumulateLoyaltyPointsRequest struct {
	AccumulatePoints *LoyaltyEventAccumulatePoints `json:"accumulate_points"`
	// A unique string that identifies the `AccumulateLoyaltyPoints` request.  Keys can be any valid string but must be unique for every request.
	IdempotencyKey string `json:"idempotency_key"`
	// The [location](https://developer.squareup.com/reference/square_2024-01-18/objects/Location) where the purchase was made.
	LocationId string `json:"location_id"`
}
