/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

type CheckoutLocationSettingsBranding struct {
	// Show the location logo on the checkout page.
	HeaderType string `json:"header_type,omitempty"`
	// The HTML-supported hex color for the button on the checkout page (for example, \"#FFFFFF\").
	ButtonColor string `json:"button_color,omitempty"`
	// The shape of the button on the checkout page.
	ButtonShape string `json:"button_shape,omitempty"`
}
