/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ShippingFee struct {
	// The name for the shipping fee.
	Name string `json:"name,omitempty"`
	Charge *Money `json:"charge"`
}
