/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Defines the parameters for a `DeprecatedCreateDisputeEvidenceFile` request.
type DeprecatedCreateDisputeEvidenceFileRequest struct {
	// The Unique ID. For more information, see [Idempotency](https://developer.squareup.com/docs/working-with-apis/idempotency).
	IdempotencyKey string `json:"idempotency_key"`
	// The type of evidence you are uploading.
	EvidenceType string `json:"evidence_type,omitempty"`
	// The MIME type of the uploaded file. The type can be image/heic, image/heif, image/jpeg, application/pdf, image/png, or image/tiff.
	ContentType string `json:"content_type,omitempty"`
}
