/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

type AcceptedPaymentMethods struct {
	// Whether Apple Pay is accepted at checkout.
	ApplePay bool `json:"apple_pay,omitempty"`
	// Whether Google Pay is accepted at checkout.
	GooglePay bool `json:"google_pay,omitempty"`
	// Whether Cash App Pay is accepted at checkout.
	CashAppPay bool `json:"cash_app_pay,omitempty"`
	// Whether Afterpay/Clearpay is accepted at checkout.
	AfterpayClearpay bool `json:"afterpay_clearpay,omitempty"`
}
