/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

type V1PaymentTaxInclusionType string

// List of V1PaymentTaxInclusionType
const (
	ADDITIVE_V1PaymentTaxInclusionType  V1PaymentTaxInclusionType = "ADDITIVE"
	INCLUSIVE_V1PaymentTaxInclusionType V1PaymentTaxInclusionType = "INCLUSIVE"
)
