/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Describes a request to update a payment using [UpdatePayment](https://developer.squareup.com/reference/square_2024-01-18/payments-api/update-payment).
type UpdatePaymentRequest struct {
	Payment *Payment `json:"payment,omitempty"`
	// A unique string that identifies this `UpdatePayment` request. Keys can be any valid string but must be unique for every `UpdatePayment` request.  For more information, see [Idempotency](https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency).
	IdempotencyKey string `json:"idempotency_key"`
}
