/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// A type-specific filter used in a [custom attribute filter](https://developer.squareup.com/reference/square_2024-01-18/objects/CustomerCustomAttributeFilter) to search based on the value  of a customer-related [custom attribute](https://developer.squareup.com/reference/square_2024-01-18/objects/CustomAttribute).
type CustomerCustomAttributeFilterValue struct {
	Email     *CustomerTextFilter `json:"email,omitempty"`
	Phone     *CustomerTextFilter `json:"phone,omitempty"`
	Text      *CustomerTextFilter `json:"text,omitempty"`
	Selection *FilterValue        `json:"selection,omitempty"`
	Date      *TimeRange          `json:"date,omitempty"`
	Number    *FloatNumberRange   `json:"number,omitempty"`
	// A filter for a query based on the value of a `Boolean`-type custom attribute.
	Boolean bool                   `json:"boolean,omitempty"`
	Address *CustomerAddressFilter `json:"address,omitempty"`
}
