/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Defines the fields that are included in the response body of a request to the [CreateRefund](https://developer.squareup.com/reference/square_2024-01-18/transactions-api/create-refund) endpoint.  One of `errors` or `refund` is present in a given response (never both).
type CreateRefundResponse struct {
	// Any errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
	Refund *Refund `json:"refund,omitempty"`
}
