/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Defines output parameters in a request to the [ChangeBillingAnchorDate](https://developer.squareup.com/reference/square_2024-01-18/subscriptions-api/change-billing-anchor-date) endpoint.
type ChangeBillingAnchorDateResponse struct {
	// Errors encountered during the request.
	Errors []ModelError `json:"errors,omitempty"`
	Subscription *Subscription `json:"subscription,omitempty"`
	// A list of a single billing anchor date change for the subscription.
	Actions []SubscriptionAction `json:"actions,omitempty"`
}
