/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// A value qualified by unit of measure.
type DeviceComponentDetailsMeasurement struct {
	Value int32 `json:"value,omitempty"`
}
