/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents a phone number.
type V1PhoneNumber struct {
	// The phone number's international calling code. For US phone numbers, this value is +1.
	CallingCode string `json:"calling_code"`
	// The phone number.
	Number string `json:"number"`
}
