/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Represents a [BulkDeleteLocationCustomAttributes](https://developer.squareup.com/reference/square_2024-01-18/location-custom-attributes-api/bulk-delete-location-custom-attributes) request.
type BulkDeleteLocationCustomAttributesRequest struct {
	// The data used to update the `CustomAttribute` objects. The keys must be unique and are used to map to the corresponding response.
}
