/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1CreateRefundRequestType string

// List of V1CreateRefundRequestType
const (
	FULL_V1CreateRefundRequestType V1CreateRefundRequestType = "FULL"
	PARTIAL_V1CreateRefundRequestType V1CreateRefundRequestType = "PARTIAL"
)
