/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Defines the fields that are included in the response body of a request to the [ListCards](https://developer.squareup.com/reference/square_2024-01-18/cards-api/list-cards) endpoint.  Note: if there are errors processing the request, the card field will not be present.
type ListCardsResponse struct {
	// Information on errors encountered during the request.
	Errors []ModelError `json:"errors,omitempty"`
	// The requested list of `Card`s.
	Cards []Card `json:"cards,omitempty"`
	// The pagination cursor to be used in a subsequent request. If empty, this is the final response.  See [Pagination](https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination) for more information.
	Cursor string `json:"cursor,omitempty"`
}
