/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Defines input parameters in a request to the  [ListSubscriptionEvents](https://developer.squareup.com/reference/square_2024-01-18/subscriptions-api/list-subscription-events) endpoint.
type ListSubscriptionEventsRequest struct {
	// When the total number of resulting subscription events exceeds the limit of a paged response,  specify the cursor returned from a preceding response here to fetch the next set of results. If the cursor is unset, the response contains the last page of the results.  For more information, see [Pagination](https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination).
	Cursor string `json:"cursor,omitempty"`
	// The upper limit on the number of subscription events to return in a paged response.
	Limit int32 `json:"limit,omitempty"`
}
