/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

type CashDrawerDevice struct {
	// The device Square-issued ID
	Id string `json:"id,omitempty"`
	// The device merchant-specified name.
	Name string `json:"name,omitempty"`
}
