/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// TaxInclusionType : Whether to the tax amount should be additional to or included in the CatalogItem price.
type TaxInclusionType string

// List of TaxInclusionType
const (
	ADDITIVE_TaxInclusionType  TaxInclusionType = "ADDITIVE"
	INCLUSIVE_TaxInclusionType TaxInclusionType = "INCLUSIVE"
)
