/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

type RetrieveCashDrawerShiftRequest struct {
	// The ID of the location to retrieve cash drawer shifts from.
	LocationId string `json:"location_id"`
}
