/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents a [BulkDeleteBookingCustomAttributes](https://developer.squareup.com/reference/square_2024-01-18/booking-custom-attributes-api/bulk-delete-booking-custom-attributes) response, which contains a map of responses that each corresponds to an individual delete request.
type BulkDeleteBookingCustomAttributesResponse struct {
	// A map of responses that correspond to individual delete requests. Each response has the same ID as the corresponding request and contains `booking_id` and  `errors` field.
	Values map[string]BookingCustomAttributeDeleteResponse `json:"values,omitempty"`
	// Any errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
}
