/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents a [CalculateLoyaltyPoints](https://developer.squareup.com/reference/square_2024-01-18/loyalty-api/calculate-loyalty-points) response.
type CalculateLoyaltyPointsResponse struct {
	// Any errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
	// The number of points that the buyer can earn from the base loyalty program.
	Points int32 `json:"points,omitempty"`
	// The number of points that the buyer can earn from a loyalty promotion. To be eligible to earn promotion points, the purchase must first qualify for program points. When `order_id` is not provided in the request, this value is always 0.
	PromotionPoints int32 `json:"promotion_points,omitempty"`
}
