/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Describes a request to retrieve a refund using [GetPaymentRefund](https://developer.squareup.com/reference/square_2024-01-18/refunds-api/get-payment-refund).
type GetPaymentRefundRequest struct {
}
