/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SignatureOptions struct {
	// The title text to display in the signature capture flow on the Terminal.
	Title string `json:"title"`
	// The body text to display in the signature capture flow on the Terminal.
	Body string `json:"body"`
	// An image representation of the collected signature.
	Signature []SignatureImage `json:"signature,omitempty"`
}
