/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

type InventoryAdjustmentGroup struct {
	// A unique ID generated by Square for the `InventoryAdjustmentGroup`.
	Id string `json:"id,omitempty"`
	// The inventory adjustment of the composed variation.
	RootAdjustmentId string `json:"root_adjustment_id,omitempty"`
	// Representative `from_state` for adjustments within the group. For example, for a group adjustment from `IN_STOCK` to `SOLD`, there can be two component adjustments in the group: one from `IN_STOCK`to `COMPOSED` and the other one from `COMPOSED` to `SOLD`. Here, the representative `from_state` for the `InventoryAdjustmentGroup` is `IN_STOCK`.
	FromState string `json:"from_state,omitempty"`
	// Representative `to_state` for adjustments within group. For example, for a group adjustment from `IN_STOCK` to `SOLD`, the two component adjustments in the group can be from `IN_STOCK` to `COMPOSED` and from `COMPOSED` to `SOLD`. Here, the representative `to_state` of the `InventoryAdjustmentGroup` is `SOLD`.
	ToState string `json:"to_state,omitempty"`
}
