/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Represents a [CreateLoyaltyPromotion](https://developer.squareup.com/reference/square_2024-01-18/loyalty-api/create-loyalty-promotion) request.
type CreateLoyaltyPromotionRequest struct {
	LoyaltyPromotion *LoyaltyPromotion `json:"loyalty_promotion"`
	// A unique identifier for this request, which is used to ensure idempotency. For more information, see [Idempotency](https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency).
	IdempotencyKey string `json:"idempotency_key"`
}
