/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// SearchCatalogItemsRequestStockLevel : Defines supported stock levels of the item inventory.
type SearchCatalogItemsRequestStockLevel string

// List of SearchCatalogItemsRequestStockLevel
const (
	OUT_SearchCatalogItemsRequestStockLevel SearchCatalogItemsRequestStockLevel = "OUT"
	LOW_SearchCatalogItemsRequestStockLevel SearchCatalogItemsRequestStockLevel = "LOW"
)
