/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Represents an output from a call to [BulkUpdateVendors](https://developer.squareup.com/reference/square_2024-01-18/vendors-api/bulk-update-vendors).
type BulkUpdateVendorsResponse struct {
	// Errors encountered when the request fails.
	Errors []ModelError `json:"errors,omitempty"`
	// A set of [UpdateVendorResponse](https://developer.squareup.com/reference/square_2024-01-18/objects/UpdateVendorResponse) objects encapsulating successfully created [Vendor](https://developer.squareup.com/reference/square_2024-01-18/objects/Vendor) objects or error responses for failed attempts. The set is represented by a collection of `Vendor`-ID/`UpdateVendorResponse`-object or  `Vendor`-ID/error-object pairs.
	Responses map[string]UpdateVendorResponse `json:"responses,omitempty"`
}
