/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckoutLocationSettingsBrandingHeaderType string

// List of CheckoutLocationSettingsBrandingHeaderType
const (
	BUSINESS_NAME_CheckoutLocationSettingsBrandingHeaderType CheckoutLocationSettingsBrandingHeaderType = "BUSINESS_NAME"
	FRAMED_LOGO_CheckoutLocationSettingsBrandingHeaderType CheckoutLocationSettingsBrandingHeaderType = "FRAMED_LOGO"
	FULL_WIDTH_LOGO_CheckoutLocationSettingsBrandingHeaderType CheckoutLocationSettingsBrandingHeaderType = "FULL_WIDTH_LOGO"
)
