/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Additional details about `WALLET` type payments with the `brand` of `CASH_APP`.
type CashAppDetails struct {
	// The name of the Cash App account holder.
	BuyerFullName string `json:"buyer_full_name,omitempty"`
	// The country of the Cash App account holder, in ISO 3166-1-alpha-2 format.  For possible values, see [Country](https://developer.squareup.com/reference/square_2024-01-18/enums/Country).
	BuyerCountryCode string `json:"buyer_country_code,omitempty"`
	// $Cashtag of the Cash App account holder.
	BuyerCashtag string `json:"buyer_cashtag,omitempty"`
}
