/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents Square-estimated quantity of items in a particular state at a particular seller location based on the known history of physical counts and inventory adjustments.
type InventoryCount struct {
	// The Square-generated ID of the [CatalogObject](https://developer.squareup.com/reference/square_2024-01-18/objects/CatalogObject) being tracked.
	CatalogObjectId string `json:"catalog_object_id,omitempty"`
	// The [type](https://developer.squareup.com/reference/square_2024-01-18/enums/CatalogObjectType) of the [CatalogObject](https://developer.squareup.com/reference/square_2024-01-18/objects/CatalogObject) being tracked.   The Inventory API supports setting and reading the `\"catalog_object_type\": \"ITEM_VARIATION\"` field value.  In addition, it can also read the `\"catalog_object_type\": \"ITEM\"` field value that is set by the Square Restaurants app.
	CatalogObjectType string `json:"catalog_object_type,omitempty"`
	// The current [inventory state](https://developer.squareup.com/reference/square_2024-01-18/enums/InventoryState) for the related quantity of items.
	State string `json:"state,omitempty"`
	// The Square-generated ID of the [Location](https://developer.squareup.com/reference/square_2024-01-18/objects/Location) where the related quantity of items is being tracked.
	LocationId string `json:"location_id,omitempty"`
	// The number of items affected by the estimated count as a decimal string. Can support up to 5 digits after the decimal point.
	Quantity string `json:"quantity,omitempty"`
	// An RFC 3339-formatted timestamp that indicates when the most recent physical count or adjustment affecting the estimated count is received.
	CalculatedAt string `json:"calculated_at,omitempty"`
	// Whether the inventory count is for composed variation (TRUE) or not (FALSE). If true, the inventory count will not be present in the response of any of these endpoints: [BatchChangeInventory](https://developer.squareup.com/reference/square_2024-01-18/inventory-api/batch-change-inventory), [BatchRetrieveInventoryChanges](https://developer.squareup.com/reference/square_2024-01-18/inventory-api/batch-retrieve-inventory-changes), [BatchRetrieveInventoryCounts](https://developer.squareup.com/reference/square_2024-01-18/inventory-api/batch-retrieve-inventory-counts), and [RetrieveInventoryChanges](https://developer.squareup.com/reference/square_2024-01-18/inventory-api/retrieve-inventory-changes).
	IsEstimated bool `json:"is_estimated,omitempty"`
}
