/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents an output from a call to [SearchVendors](https://developer.squareup.com/reference/square_2024-01-18/vendors-api/search-vendors).
type SearchVendorsResponse struct {
	// Errors encountered when the request fails.
	Errors []ModelError `json:"errors,omitempty"`
	// The [Vendor](https://developer.squareup.com/reference/square_2024-01-18/objects/Vendor) objects matching the specified search filter.
	Vendors []Vendor `json:"vendors,omitempty"`
	// The pagination cursor to be used in a subsequent request. If unset, this is the final response.  See the [Pagination](https://developer.squareup.com/docs/working-with-apis/pagination) guide for more information.
	Cursor string `json:"cursor,omitempty"`
}
