/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A node in the path from a retrieved category to its root node.
type CategoryPathToRootNode struct {
	// The category's ID.
	CategoryId string `json:"category_id,omitempty"`
	// The category's name.
	CategoryName string `json:"category_name,omitempty"`
}
