/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

type UpdatePaymentLinkResponse struct {
	// Any errors that occurred when updating the payment link.
	Errors      []ModelError `json:"errors,omitempty"`
	PaymentLink *PaymentLink `json:"payment_link,omitempty"`
}
