/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DeviceComponentDetailsApplicationDetails struct {
	// The type of application.
	ApplicationType string `json:"application_type,omitempty"`
	// The version of the application.
	Version string `json:"version,omitempty"`
	// The location_id of the session for the application.
	SessionLocation string `json:"session_location,omitempty"`
	// The id of the device code that was used to log in to the device.
	DeviceCodeId string `json:"device_code_id,omitempty"`
}
