/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

type V1ListSettlementsRequestStatus string

// List of V1ListSettlementsRequestStatus
const (
	SENT_V1ListSettlementsRequestStatus   V1ListSettlementsRequestStatus = "SENT"
	FAILED_V1ListSettlementsRequestStatus V1ListSettlementsRequestStatus = "FAILED"
)
