/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Represents a [RetrieveBookingCustomAttributeDefinition](https://developer.squareup.com/reference/square_2024-01-18/booking-custom-attributes-api/retrieve-booking-custom-attribute-definition) request.
type RetrieveBookingCustomAttributeDefinitionRequest struct {
	// The current version of the custom attribute definition, which is used for strongly consistent reads to guarantee that you receive the most up-to-date data. When included in the request, Square returns the specified version or a higher version if one exists. If the specified version is higher than the current version, Square returns a `BAD_REQUEST` error.
	Version int32 `json:"version,omitempty"`
}
