/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Lists all webhook event types that can be subscribed to.
type ListWebhookEventTypesRequest struct {
	// The API version for which to list event types. Setting this field overrides the default version used by the application.
	ApiVersion string `json:"api_version,omitempty"`
}
