/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

type DeviceComponentDetailsNetworkInterfaceDetails struct {
	// The string representation of the device’s IPv4 address.
	IpAddressV4 string `json:"ip_address_v4,omitempty"`
}
