/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Defines the fields that are included in the response body of a request to the [TestWebhookSubscription](https://developer.squareup.com/reference/square_2024-01-18/webhook-subscriptions-api/test-webhook-subscription) endpoint.  Note: If there are errors processing the request, the [SubscriptionTestResult](https://developer.squareup.com/reference/square_2024-01-18/objects/SubscriptionTestResult) field is not present.
type TestWebhookSubscriptionResponse struct {
	// Information on errors encountered during the request.
	Errors []ModelError `json:"errors,omitempty"`
	SubscriptionTestResult *SubscriptionTestResult `json:"subscription_test_result,omitempty"`
}
