/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Updates a [Subscription](https://developer.squareup.com/reference/square_2024-01-18/objects/WebhookSubscription).
type UpdateWebhookSubscriptionRequest struct {
	Subscription *WebhookSubscription `json:"subscription,omitempty"`
}
