/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Defines the fields that are included in the request body for the [RetrieveLocation](https://developer.squareup.com/reference/square_2024-01-18/locations-api/retrieve-location) endpoint.
type RetrieveLocationRequest struct {
}
