/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// TeamMemberStatus : Enumerates the possible statuses the team member can have within a business.
type TeamMemberStatus string

// List of TeamMemberStatus
const (
	ACTIVE_TeamMemberStatus   TeamMemberStatus = "ACTIVE"
	INACTIVE_TeamMemberStatus TeamMemberStatus = "INACTIVE"
)
