/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Defines supported query expressions to search for vendors by.
type SearchVendorsRequestFilter struct {
	// The names of the [Vendor](https://developer.squareup.com/reference/square_2024-01-18/objects/Vendor) objects to retrieve.
	Name []string `json:"name,omitempty"`
	// The statuses of the [Vendor](https://developer.squareup.com/reference/square_2024-01-18/objects/Vendor) objects to retrieve.
	Status []string `json:"status,omitempty"`
}
