/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// CatalogCategoryType : Indicates the type of a category.
type CatalogCategoryType string

// List of CatalogCategoryType
const (
	REGULAR_CATEGORY_CatalogCategoryType CatalogCategoryType = "REGULAR_CATEGORY"
	MENU_CATEGORY_CatalogCategoryType    CatalogCategoryType = "MENU_CATEGORY"
	KITCHEN_CATEGORY_CatalogCategoryType CatalogCategoryType = "KITCHEN_CATEGORY"
)
