/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Group of standard measurement units.
type StandardUnitDescriptionGroup struct {
	// List of standard (non-custom) measurement units in this description group.
	StandardUnitDescriptions []StandardUnitDescription `json:"standard_unit_descriptions,omitempty"`
	// IETF language tag.
	LanguageCode string `json:"language_code,omitempty"`
}
