/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// The wrapper object for the component entries of a given component type.
type Component struct {
	// The type of this component. Each component type has expected properties expressed in a structured format within its corresponding `*_details` field.
	Type_              string                                    `json:"type"`
	ApplicationDetails *DeviceComponentDetailsApplicationDetails `json:"application_details,omitempty"`
	CardReaderDetails  *DeviceComponentDetailsCardReaderDetails  `json:"card_reader_details,omitempty"`
	BatteryDetails     *DeviceComponentDetailsBatteryDetails     `json:"battery_details,omitempty"`
	WifiDetails        *DeviceComponentDetailsWiFiDetails        `json:"wifi_details,omitempty"`
	EthernetDetails    *DeviceComponentDetailsEthernetDetails    `json:"ethernet_details,omitempty"`
}
