/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Defines the fields in an `AcceptDispute` response.
type AcceptDisputeResponse struct {
	// Information about errors encountered during the request.
	Errors  []ModelError `json:"errors,omitempty"`
	Dispute *Dispute     `json:"dispute,omitempty"`
}
