/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// GiftCardType : Indicates the gift card type.
type GiftCardType string

// List of GiftCardType
const (
	PHYSICAL_GiftCardType GiftCardType = "PHYSICAL"
	DIGITAL_GiftCardType GiftCardType = "DIGITAL"
)
