/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Represents the metadata for a `POINTS_ADDITION` type of [loyalty promotion incentive](https://developer.squareup.com/reference/square_2024-01-18/objects/LoyaltyPromotionIncentive).
type LoyaltyPromotionIncentivePointsAdditionData struct {
	// The number of additional points to earn each time the promotion is triggered. For example, suppose a purchase qualifies for 5 points from the base loyalty program. If the purchase also qualifies for a `POINTS_ADDITION` promotion incentive with a `points_addition` of 3, the buyer earns a total of 8 points (5 program points + 3 promotion points = 8 points).
	PointsAddition int32 `json:"points_addition"`
}
