/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Defines output parameters in a response of the [BulkSwapPlan](https://developer.squareup.com/reference/square_2024-01-18/subscriptions-api/bulk-swap-plan) endpoint.
type BulkSwapPlanResponse struct {
	// Errors encountered during the request.
	Errors []ModelError `json:"errors,omitempty"`
	// The number of affected subscriptions.
	AffectedSubscriptions int32 `json:"affected_subscriptions,omitempty"`
}
