/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Describes query criteria for searching invoices.
type InvoiceQuery struct {
	Filter *InvoiceFilter `json:"filter"`
	Sort *InvoiceSort `json:"sort,omitempty"`
}
