/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// The settings allowed for AfterpayClearpay.
type CheckoutMerchantSettingsPaymentMethodsAfterpayClearpay struct {
	// Indicates whether the payment method is enabled for the account.
	Enabled bool `json:"enabled,omitempty"`
}
