/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// SubscriptionEventSubscriptionEventType : Supported types of an event occurred to a subscription.
type SubscriptionEventSubscriptionEventType string

// List of SubscriptionEventSubscriptionEventType
const (
	START_SUBSCRIPTION_SubscriptionEventSubscriptionEventType SubscriptionEventSubscriptionEventType = "START_SUBSCRIPTION"
	PLAN_CHANGE_SubscriptionEventSubscriptionEventType SubscriptionEventSubscriptionEventType = "PLAN_CHANGE"
	STOP_SUBSCRIPTION_SubscriptionEventSubscriptionEventType SubscriptionEventSubscriptionEventType = "STOP_SUBSCRIPTION"
	DEACTIVATE_SUBSCRIPTION_SubscriptionEventSubscriptionEventType SubscriptionEventSubscriptionEventType = "DEACTIVATE_SUBSCRIPTION"
	RESUME_SUBSCRIPTION_SubscriptionEventSubscriptionEventType SubscriptionEventSubscriptionEventType = "RESUME_SUBSCRIPTION"
	PAUSE_SUBSCRIPTION_SubscriptionEventSubscriptionEventType SubscriptionEventSubscriptionEventType = "PAUSE_SUBSCRIPTION"
	BILLING_ANCHOR_DATE_CHANGED_SubscriptionEventSubscriptionEventType SubscriptionEventSubscriptionEventType = "BILLING_ANCHOR_DATE_CHANGED"
)
