/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// CatalogQuickAmountType : Determines the type of a specific Quick Amount.
type CatalogQuickAmountType string

// List of CatalogQuickAmountType
const (
	MANUAL_CatalogQuickAmountType CatalogQuickAmountType = "QUICK_AMOUNT_TYPE_MANUAL"
	AUTO_CatalogQuickAmountType   CatalogQuickAmountType = "QUICK_AMOUNT_TYPE_AUTO"
)
