/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type V1PaymentSurchargeType string

// List of V1PaymentSurchargeType
const (
	UNKNOWN_V1PaymentSurchargeType V1PaymentSurchargeType = "UNKNOWN"
	AUTO_GRATUITY_V1PaymentSurchargeType V1PaymentSurchargeType = "AUTO_GRATUITY"
	CUSTOM_V1PaymentSurchargeType V1PaymentSurchargeType = "CUSTOM"
)
