/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Updates a [Subscription](https://developer.squareup.com/reference/square_2024-01-18/objects/WebhookSubscription) by replacing the existing signature key with a new one.
type UpdateWebhookSubscriptionSignatureKeyRequest struct {
	// A unique string that identifies the [UpdateWebhookSubscriptionSignatureKey](https://developer.squareup.com/reference/square_2024-01-18/webhook-subscriptions-api/update-webhook-subscriptionSignatureKey) request.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
}
