/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

type TerminalActionQuery struct {
	Filter *TerminalActionQueryFilter `json:"filter,omitempty"`
	Sort   *TerminalActionQuerySort   `json:"sort,omitempty"`
}
