/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Represents an output from a call to [BulkCreateVendors](https://developer.squareup.com/reference/square_2024-01-18/vendors-api/bulk-create-vendors).
type BulkCreateVendorsResponse struct {
	// Any errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
	// A set of [CreateVendorResponse](https://developer.squareup.com/reference/square_2024-01-18/objects/CreateVendorResponse) objects encapsulating successfully created [Vendor](https://developer.squareup.com/reference/square_2024-01-18/objects/Vendor) objects or error responses for failed attempts. The set is represented by  a collection of idempotency-key/`Vendor`-object or idempotency-key/error-object pairs. The idempotency keys correspond to those specified in the input.
	Responses map[string]CreateVendorResponse `json:"responses,omitempty"`
}
