/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Describes save-card action fields.
type SaveCardOptions struct {
	// The square-assigned ID of the customer linked to the saved card.
	CustomerId string `json:"customer_id"`
	// The id of the created card-on-file.
	CardId string `json:"card_id,omitempty"`
	// An optional user-defined reference ID that can be used to associate this `Card` to another entity in an external system. For example, a customer ID generated by a third-party system.
	ReferenceId string `json:"reference_id,omitempty"`
}
