/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents an `UpsertSnippet` request.
type UpsertSnippetRequest struct {
	Snippet *Snippet `json:"snippet"`
}
