/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// CatalogCustomAttributeDefinitionType : Defines the possible types for a custom attribute.
type CatalogCustomAttributeDefinitionType string

// List of CatalogCustomAttributeDefinitionType
const (
	STRING__CatalogCustomAttributeDefinitionType   CatalogCustomAttributeDefinitionType = "STRING"
	BOOLEAN_CatalogCustomAttributeDefinitionType   CatalogCustomAttributeDefinitionType = "BOOLEAN"
	NUMBER_CatalogCustomAttributeDefinitionType    CatalogCustomAttributeDefinitionType = "NUMBER"
	SELECTION_CatalogCustomAttributeDefinitionType CatalogCustomAttributeDefinitionType = "SELECTION"
)
