/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// CatalogModifierListSelectionType : Indicates whether a CatalogModifierList supports multiple selections.
type CatalogModifierListSelectionType string

// List of CatalogModifierListSelectionType
const (
	SINGLE_CatalogModifierListSelectionType   CatalogModifierListSelectionType = "SINGLE"
	MULTIPLE_CatalogModifierListSelectionType CatalogModifierListSelectionType = "MULTIPLE"
)
