/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// A request to retrieve the [loyalty program](https://developer.squareup.com/reference/square_2024-01-18/objects/LoyaltyProgram) that belongs to a seller. A seller can have only one loyalty program.
type RetrieveLoyaltyProgramRequest struct {
}
