/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents a search request for a filtered list of `TeamMember` objects.
type SearchTeamMembersRequest struct {
	Query *SearchTeamMembersQuery `json:"query,omitempty"`
	// The maximum number of `TeamMember` objects in a page (100 by default).
	Limit int32 `json:"limit,omitempty"`
	// The opaque cursor for fetching the next page. For more information, see [pagination](https://developer.squareup.com/docs/working-with-apis/pagination).
	Cursor string `json:"cursor,omitempty"`
}
