/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Represents a [DeleteMerchantCustomAttributeDefinition](https://developer.squareup.com/reference/square_2024-01-18/merchant-custom-attributes-api/delete-merchant-custom-attributeDefinition) request.
type DeleteMerchantCustomAttributeDefinitionRequest struct {
}
