/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Represents a [DeleteBookingCustomAttributeDefinition](https://developer.squareup.com/reference/square_2024-01-18/booking-custom-attributes-api/delete-booking-custom-attribute-definition) request.
type DeleteBookingCustomAttributeDefinitionRequest struct {
}
