/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// V1CreateRefundRequest
type V1CreateRefundRequest struct {
	// The ID of the payment to refund. If you are creating a `PARTIAL` refund for a split tender payment, instead provide the id of the particular tender you want to refund.
	PaymentId string `json:"payment_id"`
	// The type of refund (FULL or PARTIAL).
	Type_ string `json:"type"`
	// The reason for the refund.
	Reason string `json:"reason"`
	RefundedMoney *V1Money `json:"refunded_money,omitempty"`
	// An optional key to ensure idempotence if you issue the same PARTIAL refund request more than once.
	RequestIdempotenceKey string `json:"request_idempotence_key,omitempty"`
}
