/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// LoyaltyRewardStatus : The status of the loyalty reward.
type LoyaltyRewardStatus string

// List of LoyaltyRewardStatus
const (
	ISSUED_LoyaltyRewardStatus   LoyaltyRewardStatus = "ISSUED"
	REDEEMED_LoyaltyRewardStatus LoyaltyRewardStatus = "REDEEMED"
	DELETED_LoyaltyRewardStatus  LoyaltyRewardStatus = "DELETED"
)
