/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Represents an output from a call to [BulkRetrieveVendors](https://developer.squareup.com/reference/square_2024-01-18/vendors-api/bulk-retrieve-vendors).
type BulkRetrieveVendorsResponse struct {
	// Any errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
	// The set of [RetrieveVendorResponse](https://developer.squareup.com/reference/square_2024-01-18/objects/RetrieveVendorResponse) objects encapsulating successfully retrieved [Vendor](https://developer.squareup.com/reference/square_2024-01-18/objects/Vendor) objects or error responses for failed attempts. The set is represented by  a collection of `Vendor`-ID/`Vendor`-object or `Vendor`-ID/error-object pairs.
	Responses map[string]RetrieveVendorResponse `json:"responses,omitempty"`
}
