/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Defines the body parameters that can be included in a request to the [CreateRefund](https://developer.squareup.com/reference/square_2024-01-18/transactions-api/create-refund) endpoint.  Deprecated - recommend using [RefundPayment](https://developer.squareup.com/reference/square_2024-01-18/refunds-api/refund-payment)
type CreateRefundRequest struct {
	// A value you specify that uniquely identifies this refund among refunds you've created for the tender.  If you're unsure whether a particular refund succeeded, you can reattempt it with the same idempotency key without worrying about duplicating the refund.  See [Idempotency keys](https://developer.squareup.com/docs/working-with-apis/idempotency) for more information.
	IdempotencyKey string `json:"idempotency_key"`
	// The ID of the tender to refund.  A [`Transaction`](https://developer.squareup.com/reference/square_2024-01-18/objects/Transaction) has one or more `tenders` (i.e., methods of payment) associated with it, and you refund each tender separately with the Connect API.
	TenderId string `json:"tender_id"`
	// A description of the reason for the refund.  Default value: `Refund via API`
	Reason string `json:"reason,omitempty"`
	AmountMoney *Money `json:"amount_money"`
}
