/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Defines the body parameters that can be provided in a request to the `CreateMobileAuthorizationCode` endpoint.
type CreateMobileAuthorizationCodeRequest struct {
	// The Square location ID that the authorization code should be tied to.
	LocationId string `json:"location_id,omitempty"`
}
