/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents a [DeleteCustomerCustomAttribute](https://developer.squareup.com/reference/square_2024-01-18/customer-custom-attributes-api/delete-customer-custom-attribute) request.
type DeleteCustomerCustomAttributeRequest struct {
}
