/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// GiftCardStatus : Indicates the gift card state.
type GiftCardStatus string

// List of GiftCardStatus
const (
	ACTIVE_GiftCardStatus      GiftCardStatus = "ACTIVE"
	DEACTIVATED_GiftCardStatus GiftCardStatus = "DEACTIVATED"
	BLOCKED_GiftCardStatus     GiftCardStatus = "BLOCKED"
	PENDING_GiftCardStatus     GiftCardStatus = "PENDING"
)
