/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// InvoicePaymentReminderStatus : The status of a payment request reminder.
type InvoicePaymentReminderStatus string

// List of InvoicePaymentReminderStatus
const (
	PENDING_InvoicePaymentReminderStatus InvoicePaymentReminderStatus = "PENDING"
	NOT_APPLICABLE_InvoicePaymentReminderStatus InvoicePaymentReminderStatus = "NOT_APPLICABLE"
	SENT_InvoicePaymentReminderStatus InvoicePaymentReminderStatus = "SENT"
)
