/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Defines the parameters for a `CreateDisputeEvidenceText` request.
type CreateDisputeEvidenceTextRequest struct {
	// A unique key identifying the request. For more information, see [Idempotency](https://developer.squareup.com/docs/working-with-apis/idempotency).
	IdempotencyKey string `json:"idempotency_key"`
	// The type of evidence you are uploading.
	EvidenceType string `json:"evidence_type,omitempty"`
	// The evidence string.
	EvidenceText string `json:"evidence_text"`
}
