/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// LoyaltyAccountMappingType : The type of mapping.
type LoyaltyAccountMappingType string

// List of LoyaltyAccountMappingType
const (
	PHONE_LoyaltyAccountMappingType LoyaltyAccountMappingType = "PHONE"
)
