/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// An object describing a job that a team member is assigned to.
type JobAssignment struct {
	// The title of the job.
	JobTitle string `json:"job_title"`
	// The current pay type for the job assignment used to calculate the pay amount in a pay period.
	PayType    string `json:"pay_type"`
	HourlyRate *Money `json:"hourly_rate,omitempty"`
	AnnualRate *Money `json:"annual_rate,omitempty"`
	// The planned hours per week for the job. Set if the job `PayType` is `SALARY`.
	WeeklyHours int32 `json:"weekly_hours,omitempty"`
}
