/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CatalogDiscountModifyTaxBasis string

// List of CatalogDiscountModifyTaxBasis
const (
	MODIFY_TAX_BASIS_CatalogDiscountModifyTaxBasis CatalogDiscountModifyTaxBasis = "MODIFY_TAX_BASIS"
	DO_NOT_MODIFY_TAX_BASIS_CatalogDiscountModifyTaxBasis CatalogDiscountModifyTaxBasis = "DO_NOT_MODIFY_TAX_BASIS"
)
