/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Represents the parameters in a search for `TeamMember` objects.
type SearchTeamMembersQuery struct {
	Filter *SearchTeamMembersFilter `json:"filter,omitempty"`
}
