/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Tests a [Subscription](https://developer.squareup.com/reference/square_2024-01-18/objects/WebhookSubscription) by sending a test event to its notification URL.
type TestWebhookSubscriptionRequest struct {
	// The event type that will be used to test the [Subscription](https://developer.squareup.com/reference/square_2024-01-18/objects/WebhookSubscription). The event type must be contained in the list of event types in the [Subscription](https://developer.squareup.com/reference/square_2024-01-18/objects/WebhookSubscription).
	EventType string `json:"event_type,omitempty"`
}
