/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Provides metadata when the event `type` is `ACCUMULATE_PROMOTION_POINTS`.
type LoyaltyEventAccumulatePromotionPoints struct {
	// The Square-assigned ID of the [loyalty program](https://developer.squareup.com/reference/square_2024-01-18/objects/LoyaltyProgram).
	LoyaltyProgramId string `json:"loyalty_program_id,omitempty"`
	// The Square-assigned ID of the [loyalty promotion](https://developer.squareup.com/reference/square_2024-01-18/objects/LoyaltyPromotion).
	LoyaltyPromotionId string `json:"loyalty_promotion_id,omitempty"`
	// The number of points earned by the event.
	Points int32 `json:"points"`
	// The ID of the [order](https://developer.squareup.com/reference/square_2024-01-18/objects/Order) for which the buyer earned the promotion points. Only applications that use the Orders API to process orders can trigger this event.
	OrderId string `json:"order_id"`
}
