/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckoutLocationSettingsBrandingButtonShape string

// List of CheckoutLocationSettingsBrandingButtonShape
const (
	SQUARED_CheckoutLocationSettingsBrandingButtonShape CheckoutLocationSettingsBrandingButtonShape = "SQUARED"
	ROUNDED_CheckoutLocationSettingsBrandingButtonShape CheckoutLocationSettingsBrandingButtonShape = "ROUNDED"
	PILL_CheckoutLocationSettingsBrandingButtonShape CheckoutLocationSettingsBrandingButtonShape = "PILL"
)
