/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Request object for the [RetrieveMerchant](https://developer.squareup.com/reference/square_2024-01-18/merchants-api/retrieve-merchant) endpoint.
type RetrieveMerchantRequest struct {
}
