/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// LocationCapability : The capabilities a location might have.
type LocationCapability string

// List of LocationCapability
const (
	CREDIT_CARD_PROCESSING_LocationCapability LocationCapability = "CREDIT_CARD_PROCESSING"
	AUTOMATIC_TRANSFERS_LocationCapability    LocationCapability = "AUTOMATIC_TRANSFERS"
	UNLINKED_REFUNDS_LocationCapability       LocationCapability = "UNLINKED_REFUNDS"
)
