/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// BookingCreatorDetailsCreatorType : Supported types of a booking creator.
type BookingCreatorDetailsCreatorType string

// List of BookingCreatorDetailsCreatorType
const (
	TEAM_MEMBER_BookingCreatorDetailsCreatorType BookingCreatorDetailsCreatorType = "TEAM_MEMBER"
	CUSTOMER_BookingCreatorDetailsCreatorType BookingCreatorDetailsCreatorType = "CUSTOMER"
)
