/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents an [AdjustLoyaltyPoints](https://developer.squareup.com/reference/square_2024-01-18/loyalty-api/adjust-loyalty-points) request.
type AdjustLoyaltyPointsResponse struct {
	// Any errors that occurred during the request.
	Errors []ModelError `json:"errors,omitempty"`
	Event *LoyaltyEvent `json:"event,omitempty"`
}
