/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// LoyaltyProgramStatus : Indicates whether the program is currently active.
type LoyaltyProgramStatus string

// List of LoyaltyProgramStatus
const (
	INACTIVE_LoyaltyProgramStatus LoyaltyProgramStatus = "INACTIVE"
	ACTIVE_LoyaltyProgramStatus LoyaltyProgramStatus = "ACTIVE"
)
