/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// ComponentComponentType : An enum for ComponentType.
type ComponentComponentType string

// List of ComponentComponentType
const (
	APPLICATION_ComponentComponentType ComponentComponentType = "APPLICATION"
	CARD_READER_ComponentComponentType ComponentComponentType = "CARD_READER"
	BATTERY_ComponentComponentType     ComponentComponentType = "BATTERY"
	WIFI_ComponentComponentType        ComponentComponentType = "WIFI"
	ETHERNET_ComponentComponentType    ComponentComponentType = "ETHERNET"
	PRINTER_ComponentComponentType     ComponentComponentType = "PRINTER"
)
