/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// GiftCardActivityUnblockReason : Indicates the reason for unblocking a [gift card](https://developer.squareup.com/reference/square_2024-01-18/objects/GiftCard).
type GiftCardActivityUnblockReason string

// List of GiftCardActivityUnblockReason
const (
	CHARGEBACK_UNBLOCK_GiftCardActivityUnblockReason GiftCardActivityUnblockReason = "CHARGEBACK_UNBLOCK"
)
