/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents a promotion for a [loyalty program](https://developer.squareup.com/reference/square_2024-01-18/objects/LoyaltyProgram). Loyalty promotions enable buyers to earn extra points on top of those earned from the base program.  A loyalty program can have a maximum of 10 loyalty promotions with an `ACTIVE` or `SCHEDULED` status.
type LoyaltyPromotion struct {
	// The Square-assigned ID of the promotion.
	Id string `json:"id,omitempty"`
	// The name of the promotion.
	Name string `json:"name"`
	Incentive *LoyaltyPromotionIncentive `json:"incentive"`
	AvailableTime *LoyaltyPromotionAvailableTimeData `json:"available_time"`
	TriggerLimit *LoyaltyPromotionTriggerLimit `json:"trigger_limit,omitempty"`
	// The current status of the promotion.
	Status string `json:"status,omitempty"`
	// The timestamp of when the promotion was created, in RFC 3339 format.
	CreatedAt string `json:"created_at,omitempty"`
	// The timestamp of when the promotion was canceled, in RFC 3339 format.
	CanceledAt string `json:"canceled_at,omitempty"`
	// The timestamp when the promotion was last updated, in RFC 3339 format.
	UpdatedAt string `json:"updated_at,omitempty"`
	// The ID of the [loyalty program](https://developer.squareup.com/reference/square_2024-01-18/objects/LoyaltyProgram) associated with the promotion.
	LoyaltyProgramId string `json:"loyalty_program_id,omitempty"`
	MinimumSpendAmountMoney *Money `json:"minimum_spend_amount_money,omitempty"`
	// The IDs of any qualifying `ITEM_VARIATION` [catalog objects](https://developer.squareup.com/reference/square_2024-01-18/objects/CatalogObject). If specified, the purchase must include at least one of these items to qualify for the promotion.  This option is valid only if the base loyalty program uses a `VISIT` or `SPEND` accrual rule. With `SPEND` accrual rules, make sure that qualifying promotional items are not excluded.  You can specify `qualifying_item_variation_ids` or `qualifying_category_ids` for a given promotion, but not both.
	QualifyingItemVariationIds []string `json:"qualifying_item_variation_ids"`
	// The IDs of any qualifying `CATEGORY` [catalog objects](https://developer.squareup.com/reference/square_2024-01-18/objects/CatalogObject). If specified, the purchase must include at least one item from one of these categories to qualify for the promotion.  This option is valid only if the base loyalty program uses a `VISIT` or `SPEND` accrual rule. With `SPEND` accrual rules, make sure that qualifying promotional items are not excluded.  You can specify `qualifying_category_ids` or `qualifying_item_variation_ids` for a promotion, but not both.
	QualifyingCategoryIds []string `json:"qualifying_category_ids"`
}
