/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Represents filtering and sorting criteria for a [SearchCustomers](https://developer.squareup.com/reference/square_2024-01-18/customers-api/search-customers) request.
type CustomerQuery struct {
	Filter *CustomerFilter `json:"filter,omitempty"`
	Sort *CustomerSort `json:"sort,omitempty"`
}
