/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// ChangeTiming : Supported timings when a pending change, as an action, takes place to a subscription.
type ChangeTiming string

// List of ChangeTiming
const (
	IMMEDIATE_ChangeTiming ChangeTiming = "IMMEDIATE"
	END_OF_BILLING_CYCLE_ChangeTiming ChangeTiming = "END_OF_BILLING_CYCLE"
)
