/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// V1TenderCardBrand : The brand of a credit card.
type V1TenderCardBrand string

// List of V1TenderCardBrand
const (
	OTHER_BRAND_V1TenderCardBrand      V1TenderCardBrand = "OTHER_BRAND"
	VISA_V1TenderCardBrand             V1TenderCardBrand = "VISA"
	MASTER_CARD_V1TenderCardBrand      V1TenderCardBrand = "MASTER_CARD"
	AMERICAN_EXPRESS_V1TenderCardBrand V1TenderCardBrand = "AMERICAN_EXPRESS"
	DISCOVER_V1TenderCardBrand         V1TenderCardBrand = "DISCOVER"
	DISCOVER_DINERS_V1TenderCardBrand  V1TenderCardBrand = "DISCOVER_DINERS"
	JCB_V1TenderCardBrand              V1TenderCardBrand = "JCB"
	CHINA_UNIONPAY_V1TenderCardBrand   V1TenderCardBrand = "CHINA_UNIONPAY"
	SQUARE_GIFT_CARD_V1TenderCardBrand V1TenderCardBrand = "SQUARE_GIFT_CARD"
)
