/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The payment methods that customers can use to pay an [invoice](https://developer.squareup.com/reference/square_2024-01-18/objects/Invoice) on the Square-hosted invoice payment page.
type InvoiceAcceptedPaymentMethods struct {
	// Indicates whether credit card or debit card payments are accepted. The default value is `false`.
	Card bool `json:"card,omitempty"`
	// Indicates whether Square gift card payments are accepted. The default value is `false`.
	SquareGiftCard bool `json:"square_gift_card,omitempty"`
	// Indicates whether ACH bank transfer payments are accepted. The default value is `false`.
	BankAccount bool `json:"bank_account,omitempty"`
	// Indicates whether Afterpay (also known as Clearpay) payments are accepted. The default value is `false`.  This option is allowed only for invoices that have a single payment request of the `BALANCE` type. This payment method is supported if the seller account accepts Afterpay payments and the seller location is in a country where Afterpay invoice payments are supported. As a best practice, consider enabling an additional payment method when allowing `buy_now_pay_later` payments. For more information, including detailed requirements and processing limits, see [Buy Now Pay Later payments with Afterpay](https://developer.squareup.com/docs/invoices-api/overview#buy-now-pay-later).
	BuyNowPayLater bool `json:"buy_now_pay_later,omitempty"`
	// Indicates whether Cash App payments are accepted. The default value is `false`.  This payment method is supported only for seller [locations](https://developer.squareup.com/reference/square_2024-01-18/objects/Location) in the United States.
	CashAppPay bool `json:"cash_app_pay,omitempty"`
}
