/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Represents the arguments used to construct a new phase.
type PhaseInput struct {
	// index of phase in total subscription plan
	Ordinal int64 `json:"ordinal"`
	// id of order to be used in billing
	OrderTemplateId string `json:"order_template_id,omitempty"`
}
