/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// BusinessBookingProfileCustomerTimezoneChoice : Choices of customer-facing time zone used for bookings.
type BusinessBookingProfileCustomerTimezoneChoice string

// List of BusinessBookingProfileCustomerTimezoneChoice
const (
	BUSINESS_LOCATION_TIMEZONE_BusinessBookingProfileCustomerTimezoneChoice BusinessBookingProfileCustomerTimezoneChoice = "BUSINESS_LOCATION_TIMEZONE"
	CUSTOMER_CHOICE_BusinessBookingProfileCustomerTimezoneChoice            BusinessBookingProfileCustomerTimezoneChoice = "CUSTOMER_CHOICE"
)
