/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// Retrieves details for a specific Card. Accessible via HTTP requests at GET https://connect.squareup.com/v2/cards
type ListCardsRequest struct {
	// A pagination cursor returned by a previous call to this endpoint. Provide this to retrieve the next set of results for your original query.  See [Pagination](https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination) for more information.
	Cursor string `json:"cursor,omitempty"`
	// Limit results to cards associated with the customer supplied. By default, all cards owned by the merchant are returned.
	CustomerId string `json:"customer_id,omitempty"`
	// Includes disabled cards. By default, all enabled cards owned by the merchant are returned.
	IncludeDisabled bool `json:"include_disabled,omitempty"`
	// Limit results to cards associated with the reference_id supplied.
	ReferenceId string `json:"reference_id,omitempty"`
	// Sorts the returned list by when the card was created with the specified order. This field defaults to ASC.
	SortOrder string `json:"sort_order,omitempty"`
}
