/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

// LoyaltyEventSource : Defines whether the event was generated by the Square Point of Sale.
type LoyaltyEventSource string

// List of LoyaltyEventSource
const (
	SQUARE_LoyaltyEventSource      LoyaltyEventSource = "SQUARE"
	LOYALTY_API_LoyaltyEventSource LoyaltyEventSource = "LOYALTY_API"
)
