/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

type SignatureImage struct {
	// The mime/type of the image data. Use `image/png;base64` for png.
	ImageType string `json:"image_type,omitempty"`
	// The base64 representation of the image.
	Data string `json:"data,omitempty"`
}
