/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package squareup

type CheckoutMerchantSettingsPaymentMethods struct {
	ApplePay         *PaymentMethod    `json:"apple_pay,omitempty"`
	GooglePay        *PaymentMethod    `json:"google_pay,omitempty"`
	CashApp          *PaymentMethod    `json:"cash_app,omitempty"`
	AfterpayClearpay *AfterpayClearpay `json:"afterpay_clearpay,omitempty"`
}
