/*
 * Square Connect API
 *
 * Client library for accessing the Square Connect APIs
 *
 * API version: 2.0
 * Contact: developers@squareup.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Provides metadata when the event `type` is `REDEEM_REWARD`.
type LoyaltyEventRedeemReward struct {
	// The ID of the [loyalty program](https://developer.squareup.com/reference/square_2024-01-18/objects/LoyaltyProgram).
	LoyaltyProgramId string `json:"loyalty_program_id"`
	// The ID of the redeemed [loyalty reward](https://developer.squareup.com/reference/square_2024-01-18/objects/LoyaltyReward). This field is returned only if the event source is `LOYALTY_API`.
	RewardId string `json:"reward_id,omitempty"`
	// The ID of the [order](https://developer.squareup.com/reference/square_2024-01-18/objects/Order) that redeemed the reward. This field is returned only if the Orders API is used to process orders.
	OrderId string `json:"order_id,omitempty"`
}
